name: push then build with react resource
on:
  push:
    paths:
      - 'source/**'
      - '.github/**'
    branches-ignore:
      - release
  workflow_dispatch:
    branches-ignore:
      - release
  pull_request:
    paths:
      - 'source/**'
      - '.github/**'

jobs:
  build-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Install Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: lts/hydrogen
          # https://nodejs.org/ja/download/releases latest LTS
      - name: install
        run: |
          npm install
        working-directory: source/src
      - name: Build
        run: |
          npm run build
        working-directory: source/src

